import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";

/*
 * Every stylesheet in the app is imported here, and only here, because the
 * cascade depends on this order and must not vary from route to route. Each
 * section's `theme.css` is the original theme's compiled CSS for that section,
 * generated by scripts/prepare-theme.mjs; `styles.css` is authored by us.
 *
 * The section order below is the order the original theme linked them in.
 */
import "@/styles/theme/fonts.css";
import "@/styles/theme/variables.css";
import "@/styles/theme/theme.scss.css";
import "@/sections/header/theme.css";
import "@/sections/search/theme.css";
import "@/sections/cart-drawer/theme.css";
import "@/sections/hero/theme.css";
import "@/sections/mission/theme.css";
import "@/sections/product-tabs/theme.css";
import "@/sections/craftsmanship/theme.css";
import "@/sections/menswear/theme.css";
import "@/sections/bridal/theme.css";
import "@/sections/focus/theme.css";
import "@/sections/latest-news/theme.css";
import "@/sections/instagram/theme.css";
import "@/sections/footer/theme.css";

// Ours, last, so it can build on the theme's variables and type classes. No
// selector is shared between these files, so their relative order is immaterial.
import "@/styles/pages.css";
import "@/sections/search/styles.css";
import "@/sections/footer/styles.css";
import "@/sections/checkout/styles.css";

import content from "@/data/content";
import ThemeScripts from "@/components/ThemeScripts";

const { meta } = content;

export const metadata: Metadata = {
  title: meta.title,
  description: meta.description,
  applicationName: meta.siteName,
  icons: { icon: meta.favicon },
  openGraph: {
    type: "website",
    siteName: meta.siteName,
    title: meta.title,
    description: meta.description,
  },
  twitter: {
    card: "summary_large_image",
    title: meta.title,
    description: meta.description,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
        <ThemeScripts />
      </body>
    </html>
  );
}
